package api

import (
	"fmt"
	"time"

	"github.com/zeroberto/go-ms-template/model"
)

// ExampleAPI contains the api methods available for the Example model
type ExampleAPI interface {
	// Create creates a new Example
	Create(example model.Example) Response
	// Delete deletes an existing Example
	Delete(ID int64) Response
	// Get provides all Examples
	Get() Response
	// GetByID provides an Example via an ID
	GetByID(ID int64) Response
	// PartialUpdate updates the properties of an existing Example
	PartialUpdate(ID int64, properties map[string]interface{}) Response
	// Update updates or creates, if it does not exist, a complete Example
	Update(ID int64, example model.Example) Response
}

// Response represents the request response
type Response struct {
	Code int
	Path int64
	Body interface{}
}

// ResponseBody represents the standard response body
type ResponseBody struct {
	Time    time.Time
	Message string
	Code    int
}

// Error is responsible for encapsulating errors generated by API methods
type Error struct {
	Cause    error
	Response Response
}

func (err *Error) Error() string {
	return fmt.Sprintf("%v %s", err.Response.Code, err.Cause.Error())
}
